CREATE TABLE flights_julian (
          year integer,
          month integer,
          dayofmonth integer,
          dayofweek integer,
          deptime double precision,
          crsdeptime double precision,
          arrtime double precision,
          crsarrtime double precision,
          uniquecarrier character varying(30),
          flightnum integer,
          tailnum character varying(30),
          actualelapsedtime double precision,
          crselapsedtime double precision,
          airtime double precision,
          arrdelay double precision,
          depdelay double precision,
          origin character varying(30),
          dest character varying(30),
          distance double precision,
          taxiin double precision,
          taxiout double precision,
          cancelled integer,
          cancellationcode character varying(30),
          diverted integer,
          carrierdelay double precision,
          weatherdelay double precision,
          nasdelay double precision,
          securitydelay double precision,
          lateaircraftdelay double precision,
          julian_date int -- extract(julian from make_date(year, month, dayofmonth))
);

create index on flight_julian using abtree(julian_date) with (aggregation_type = int8, agg_support = abt_count_support);
